<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Supplier;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;

/**
 * Seeds products, the "Le Bon Plan" category and suppliers imported from the
 * "Etat de Stock Le Bon Plan" stock spreadsheet (latest sheet: January 2025).
 *
 * Note: the source spreadsheet only contains products and suppliers. It has no
 * customer or dedicated category data, so a single category is created to hold
 * the imported products. Prices in the sheet are expressed in dinars/millimes
 * (3 decimals) but the products table stores integer costs, so unit prices are
 * rounded to the nearest integer.
 */
class LeBonPlanSeeder extends Seeder
{
    public function run(): void
    {
        Model::unguard();

        $category = Category::firstOrCreate(
            ['category_code' => 'CA_LBP'],
            ['category_name' => 'Le Bon Plan']
        );

        // Suppliers imported from the spreadsheet (column "Fournisseur").
        $supplierNames = [
            'Omar Abdelkefi',
            'Euro Equipement',
            'Ramzi Ayedi',
            'Naim Makni',
            'Ami',
            'Brahim',
            'Ahmed',
            'Monji ben Hamed',
            'ceg',
            'Ben Halima',
            'Hamdi cheville',
            'Sofien Tayau',
            'Trabelsi Taloche',
            'Hadj Tayeb',
            'Hammemi seau de maçon',
            'Brima colle',
            'Nader Makni',
            'Samir Gwiaa',
            'Amal',
            'luxplat',
        ];

        $suppliers = [];
        foreach ($supplierNames as $name) {
            $suppliers[$name] = Supplier::firstOrCreate(['supplier_name' => $name]);
        }

        // Products imported from the spreadsheet: [name, cost, price, supplier].
        $products = [
            ['fixation toilette laterale k2s (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['vis 4x30 blanc (eech)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['agraffe 10', 11, 11, null],
            ['bouchon pvc 100 (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['attache tableau', 0, 0, null],
            ['flexible raccord 15/15 f/f (omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['flexible raccord 15/15 m/f (Omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['baguette 3,2 bleu (omar)', 18, 18, $suppliers['Omar Abdelkefi'] ?? null],
            ['baguette 3,2 rouje (omar)', 18, 18, $suppliers['Omar Abdelkefi'] ?? null],
            ['balais contonner (naim)', 2, 2, $suppliers['Naim Makni'] ?? null],
            ['reduction pvc 100x63 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['Bidon hydrolatex (omar)', 6, 6, $suppliers['Omar Abdelkefi'] ?? null],
            ['charniere invisible courte (eechéque)', 1, 1, $suppliers['Euro Equipement'] ?? null],
            ['tirphon 8x70 (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['bouchon pvc 63 (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['bouchon pvc 80 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['collier multicouche 16 had (ahmed)', 0, 0, $suppliers['Ahmed'] ?? null],
            ['vis 4x40 jaune (omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['vis th 6x50 avec ecrou (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['BROSSE CIRCULAIRE A TIGE 50 MM (eechéque)', 2, 2, $suppliers['Euro Equipement'] ?? null],
            ['BROSSE CIRCULAIRE A TIGE 75 MM (eechéque)', 2, 2, $suppliers['Euro Equipement'] ?? null],
            ['BROSSE CONique 50 MM SUR TIGE (eechéque)', 2, 2, $suppliers['Euro Equipement'] ?? null],
            ['brosse conique 75 mm m14 (eechéque)', 3, 3, $suppliers['Euro Equipement'] ?? null],
            ['vis 3x20 blanc (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['brosse plafonner (naim)', 2, 2, $suppliers['Naim Makni'] ?? null],
            ['canniveau 30 cm (ayedi sanitaire)', 23, 23, $suppliers['Ramzi Ayedi'] ?? null],
            ['Canniveau 70 cm (ayedi sanitaire)', 34, 34, $suppliers['Ramzi Ayedi'] ?? null],
            ['cartouche mini laqué (naim)', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['charniére espagnol droite hhr (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['vis th 12x50 (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['charniére invisible danco', 1, 1, null],
            ['bouchon laiton 1/2 m amecap (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['etagere d\' angle gm lux plast (omar)', 17, 17, $suppliers['Omar Abdelkefi'] ?? null],
            ['cheville 10', 0, 0, null],
            ['cheville 12', 0, 0, null],
            ['cheville 6', 0, 0, null],
            ['cheville 8', 0, 0, null],
            ['charniere fixe 50 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['cheville de 12 had', 0, 0, null],
            ['chaine galvansié 17 3mm', 1, 1, null],
            ['chaine galvansié 19 4mm', 2, 2, null],
            ['colle mdf 200 ml sibax', 6, 6, null],
            ['colle mdf 400 ml sibax', 10, 10, null],
            ['Colle melangeur evier mural Sifam', 22, 22, null],
            ['degrippant wd-40 250ml (monji)', 11, 11, $suppliers['Monji ben Hamed'] ?? null],
            ['collier 16 sico', 0, 0, null],
            ['collier 40 sico', 0, 0, null],
            ['COLLIER GALV 63 (ayedi sanitaire)', 1, 1, $suppliers['Ramzi Ayedi'] ?? null],
            ['COLLIER GALV 100 (ayedi sanitaire)', 1, 1, $suppliers['Ramzi Ayedi'] ?? null],
            ['collier multicouche 16 (ayedi sanitaire)', 0, 0, $suppliers['Ramzi Ayedi'] ?? null],
            ['collier multicouche 20 (ayedi sanitaire)', 0, 0, $suppliers['Ramzi Ayedi'] ?? null],
            ['COLLIER SICOV 50', 0, 0, null],
            ['vis 5x70 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['console de vitre GM', 1, 1, null],
            ['console de vitre MM', 1, 1, null],
            ['console étager 200/150', 1, 1, null],
            ['Console etagere 300x250 amig', 4, 4, null],
            ['fixation bidet inox had (ahmed)', 2, 2, $suppliers['Ahmed'] ?? null],
            ['couteau mastic 16 cm', 4, 4, null],
            ['couteau mastic 18cm', 5, 5, null],
            ['couteau mastic 20 cm', 5, 5, null],
            ['couteau mastic 22 acem', 5, 5, null],
            ['culotte pvc 100 double', 8, 8, null],
            ['degripant expresse 300 ml (omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['detendeur gaz 37 mondial italy (omar)', 12, 12, $suppliers['Omar Abdelkefi'] ?? null],
            ['disque diamant uni 230 acem', 24, 24, null],
            ['bouchon pvc joint 15/21 (had)', 0, 0, null],
            ['disque diamon 125', 5, 5, null],
            ['embout clé male 3mm imp (eec )', 1, 1, null],
            ['disque ebarber 125', 3, 3, null],
            ['couteau mastic 14 (omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['disque pierre 230 (EBH)', 5, 5, null],
            ['couteau mastic 10 (omar', 4, 4, null],
            ['dulion 1l Amal', 4, 4, null],
            ['ecrou 10', 0, 0, null],
            ['ECROU 12 noir', 0, 0, null],
            ['ecrou 14 galv', 0, 0, null],
            ['ecrou 16', 0, 0, null],
            ['ecrou 5', 0, 0, null],
            ['ecrou 6', 0, 0, null],
            ['ecrou 8', 0, 0, null],
            ['vis th 12x60 (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['embout ph2 x50 double sattiné', 1, 1, null],
            ['kit de douche tresse blanc ejim douchette a,c (monji)', 11, 11, $suppliers['Monji ben Hamed'] ?? null],
            ['ENSEMBLE DE DOUCHE EJIM (monji)', 10, 10, $suppliers['Monji ben Hamed'] ?? null],
            ['equerre 30x30', 0, 0, null],
            ['te pvc 63 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['equerre plat 80', 0, 0, null],
            ['Escence 1l Amal', 3, 3, null],
            ['flexible melangeur 12', 4, 4, null],
            ['étager coin blanc (ayedi sanitaire)', 9, 9, $suppliers['Ramzi Ayedi'] ?? null],
            ['collection 3 pieces blanc (ayedi sanitaire)', 18, 18, $suppliers['Ramzi Ayedi'] ?? null],
            ['console lavabo 52 (ayedi sanitaire)', 4, 4, $suppliers['Ramzi Ayedi'] ?? null],
            ['kg fil d\'attache (omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['lame cutter acem', 3, 3, null],
            ['culotte pvc 63 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['fixation lavabo (ayedi sanitaire)', 1, 1, $suppliers['Ramzi Ayedi'] ?? null],
            ['FIXATION TOILETTE (ayedi sanitaire)', 1, 1, $suppliers['Ramzi Ayedi'] ?? null],
            ['flexible de toilette pvc (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['Flexible raccord 15x15 F/F', 4, 4, null],
            ['mecanisme tiret lux plast', 11, 11, null],
            ['jeux de 2 tetine', 2, 2, null],
            ['jeux de brosse 3pcs', 5, 5, null],
            ['chaine galvanisé 21 5mm', 3, 3, null],
            ['chaine galvanisé 30', 10, 10, null],
            ['ensemble de dOUCHE lux plast (omar)', 8, 8, $suppliers['Omar Abdelkefi'] ?? null],
            ['vis 4x20 blanc', 0, 0, null],
            ['vis th 8x60', 0, 0, null],
            ['robinet equerre amecap (omar)', 12, 12, $suppliers['Omar Abdelkefi'] ?? null],
            ['flexible raccord 12x12 f/f (monji)', 4, 4, $suppliers['Monji ben Hamed'] ?? null],
            ['lance d\' eau reglable avec porte tayou', 3, 3, null],
            ['laqué 100 g noir+couleur brillant soutinol', 1, 1, null],
            ['laqué 100 g blanc brillant soutinol', 2, 2, null],
            ['Laqué sotumail brillant blanc 1kg', 10, 10, null],
            ['Laqué sotumail brillant noir 1kg', 10, 10, null],
            ['lime tiers 4" made mexico', 8, 8, null],
            ['manche balai ben hlima 1,5 métre', 2, 2, null],
            ['MANCHE DE PELLE BEN HLIMA 1 M', 3, 3, null],
            ['MANCHE DE pelle BEN HLIMA 1,2 M', 4, 4, null],
            ['manche de pelle INTER BROSSE (naim)', 4, 4, $suppliers['Naim Makni'] ?? null],
            ['manche ratteau ben hlima', 2, 2, null],
            ['niveau d\' eau 60 cm acem (omar)', 15, 15, $suppliers['Omar Abdelkefi'] ?? null],
            ['manchon bargataire 25', 2, 2, null],
            ['Marteau arrachclou acem', 15, 15, null],
            ['Mecanisme poussoir Ejim', 22, 22, null],
            ['mecanisme poussoir lux plast', 16, 16, null],
            ['Mecanisme tirette Ejim', 14, 14, null],
            ['ratteau 12 dent acem (omar)', 7, 7, $suppliers['Omar Abdelkefi'] ?? null],
            ['meche 10 tit', 2, 2, null],
            ['meche 3 tit', 0, 0, null],
            ['meche 4 tit', 0, 0, null],
            ['meche 5 tit', 0, 0, null],
            ['métre grillage 25x4x1m (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['meche 6 tit', 1, 1, null],
            ['degrippant 6x1 (omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['meche 8 tit', 1, 1, null],
            ['meche 6 diager (ceg)', 2, 2, $suppliers['ceg'] ?? null],
            ['meche 8 diager (ceg)', 2, 2, $suppliers['ceg'] ?? null],
            ['meche 10 diager (ceg)', 3, 3, $suppliers['ceg'] ?? null],
            ['meche sds 6x160', 2, 2, null],
            ['tube colle tangit 50g (eec)', 3, 3, null],
            ['meche sds 8x160', 2, 2, null],
            ['MELANGEUR LAVABO SALAKTA', 79, 79, null],
            ['METRE GRILLAGE 25X4X100', 1, 1, null],
            ['meche 10 tita (eec)', 2, 2, null],
            ['tube colle tangit 125g (eec)', 7, 7, null],
            ['METRE GRILLAGE fIBRE 50 (blanc)', 0, 0, null],
            ['METRE GRILLAGE FIBRE 30 (orangé)', 0, 0, null],
            ['métre grillage fibre 30 50m', 0, 0, null],
            ['métre grillage fibre 30 supper monji ben hamed', 1, 1, null],
            ['métre grillage fibre 50 50m', 0, 0, null],
            ['métre grillage fibre 50 supper monji ben hamed', 1, 1, null],
            ['METRE MOUSTIQUERE METAL 1,2', 5, 5, null],
            ['degrippant sibax 200 ml', 4, 4, null],
            ['vis 5x40 jaune (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['niveau d\'eau antichoque 50 brico', 37, 37, null],
            ['niveau d\'eau antichoque 60 brico', 42, 42, null],
            ['Niveau d\'eau 50 cm Acem', 13, 13, null],
            ['Palette denté 20cm Briko', 3, 3, null],
            ['Palette denté 25cm Briko', 4, 4, null],
            ['Papier coulon 20x30cm', 1, 1, null],
            ['PATE A VIS 7X40', 0, 0, null],
            ['patte a joint', 3, 3, null],
            ['paumelle 110x55x2,5 D (ami)', 1, 1, $suppliers['Ami'] ?? null],
            ['paumelle 110x55x2,5 G (ami)', 1, 1, $suppliers['Ami'] ?? null],
            ['paumelle 140x55x2,5 D (ami)', 2, 2, $suppliers['Ami'] ?? null],
            ['paumelle 140x55x2,5 G (ami)', 2, 2, $suppliers['Ami'] ?? null],
            ['bobine n 36 (ami)', 2, 2, $suppliers['Ami'] ?? null],
            ['bobine n 18 (ami)', 2, 2, $suppliers['Ami'] ?? null],
            ['pelle 27 acem', 11, 11, null],
            ['pelle 29', 8, 8, null],
            ['vis 5x80', 0, 0, null],
            ['pinceau 60 cristal (omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['coude barg 32/26 m (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['pinceau 20 (naim)', 0, 0, $suppliers['Naim Makni'] ?? null],
            ['pinceau 30 (naim)', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['pinceau 40 (naim)', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['pinceau 50 (naim)', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['pinceau 60 (naim)', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['pinceau 70 (naim)', 2, 2, $suppliers['Naim Makni'] ?? null],
            ['coude bargat 25/15f (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['coude bargat 25/15m (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['raccord bargat 25/15f (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['miroire 1/2 rond lux plast (omar)', 27, 27, $suppliers['Omar Abdelkefi'] ?? null],
            ['pinceau cristal 50 (omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['pinceau cristal 70 (omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['pinceau rond n 6 (naim)', 3, 3, $suppliers['Naim Makni'] ?? null],
            ['pipe droit lux plast (monji)', 4, 4, $suppliers['Monji ben Hamed'] ?? null],
            ['pistolet de peintire 4001 -c', 38, 38, null],
            ['pistolet de peintire s990s', 24, 24, null],
            ['pistolet de peinture h-827p', 34, 34, null],
            ['filtre a tamis 1 pouce avec bouchon', 13, 13, null],
            ['pompe retouche blanc bril', 4, 4, null],
            ['pompe retouche noir bril', 4, 4, null],
            ['press contrôle', 54, 54, null],
            ['raccord bargataire 25/1/2M', 1, 1, null],
            ['raccord bargataire 32/26 m', 2, 2, null],
            ['raccord pist gonf', 2, 2, null],
            ['ratteau 12 dent ami', 7, 7, null],
            ['te barg 25x1/2 f', 3, 3, null],
            ['boite teinte laqué 100g bleu (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['boite teinte laqué 100g rouje (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['rivet 3,8x14', 0, 0, null],
            ['roue piv 50 rouje', 1, 1, null],
            ['roue piv 80 noire', 4, 4, null],
            ['miroir ovale abs (omar)', 21, 21, $suppliers['Omar Abdelkefi'] ?? null],
            ['roue piv 75mm poly lux', 7, 7, null],
            ['téte robinet jardin', 7, 7, null],
            ['duliant 1 l sotach (omar)', 7, 7, $suppliers['Omar Abdelkefi'] ?? null],
            ['rondelle 10x30 (brahim)', 0, 0, null],
            ['rondelle 12x30 (brahim)', 0, 0, null],
            ['rondelle 14x26 (brahim)', 0, 0, null],
            ['rondelle 16x30 (brahim)', 0, 0, null],
            ['rondellle 6x22x2,5', 0, 0, null],
            ['Rondelle 18X40x4 (brahim)', 0, 0, null],
            ['rondelle 4x12 (brahim)', 0, 0, null],
            ['rondelle 5x12 (brahim)', 0, 0, null],
            ['rondelle 6x26x1 (brahim)', 0, 0, null],
            ['rondelle 8x26x1 (brahim)', 0, 0, null],
            ['roue pivot 38mm', 1, 1, null],
            ['roue pivot 50 mm', 1, 1, null],
            ['roue pivot 160mm noir', 20, 20, null],
            ['roue pivottante 30 mm', 1, 1, null],
            ['rouleau antigoute (naim)', 3, 3, $suppliers['Naim Makni'] ?? null],
            ['rouleau mini laqué (naim)', 2, 2, $suppliers['Naim Makni'] ?? null],
            ['rouleau ravallement (naim)', 3, 3, $suppliers['Naim Makni'] ?? null],
            ['rouleau teflon a gaz briko', 2, 2, null],
            ['cartouche filtre bobine imp', 4, 4, null],
            ['roulette antigoute cristal', 7, 7, null],
            ['roulette ravallement cristal', 6, 6, null],
            ['porte papier toilette plast lux plast', 7, 7, null],
            ['seau de maçon', 2, 2, null],
            ['vis th 10x60 avec ecrou', 0, 0, null],
            ['serrure encastré b40 mts', 16, 16, null],
            ['duliant sotach 0,85l (omar)', 10, 10, $suppliers['Omar Abdelkefi'] ?? null],
            ['serrure encastré rev 22 MTS', 6, 6, null],
            ['SIPHON 10 INOX (ayedi sanitaire)', 3, 3, $suppliers['Ramzi Ayedi'] ?? null],
            ['siphon 10x10 plastique avec coude (ayedi sanitaire)', 2, 2, $suppliers['Ramzi Ayedi'] ?? null],
            ['siphon 10x10 plastique normal (ayedi sanitaire)', 1, 1, $suppliers['Ramzi Ayedi'] ?? null],
            ['SIPHON 12 INOX (ayedi sanitaire)', 4, 4, $suppliers['Ramzi Ayedi'] ?? null],
            ['SIPHON 12X12 PLASTIQUE AVEC COUDE (ayedi sanitaire)', 2, 2, $suppliers['Ramzi Ayedi'] ?? null],
            ['SIPHON 12X12 PLASTIQUE NORMAL (ayedi sanitaire)', 2, 2, $suppliers['Ramzi Ayedi'] ?? null],
            ['SIPHON 15 INOX (ayedi sanitaire)', 5, 5, $suppliers['Ramzi Ayedi'] ?? null],
            ['siphon 15x15 plastique avec coude (ayedi sanitaire)', 3, 3, $suppliers['Ramzi Ayedi'] ?? null],
            ['siphon 15x15 plastique normal (ayedi sanitaire)', 2, 2, $suppliers['Ramzi Ayedi'] ?? null],
            ['SIPHON ORIENTABLE INOX 12 (ayedi sanitaire)', 8, 8, $suppliers['Ramzi Ayedi'] ?? null],
            ['SIPHON ORIENTABLE INOX 15 (ayedi sanitaire)', 9, 9, $suppliers['Ramzi Ayedi'] ?? null],
            ['siphon plastic 15X15 avec coude HAD', 3, 3, null],
            ['SIPHON PLASTIC 15X15 HAD', 2, 2, null],
            ['Support tube argent T34 simple', 1, 1, null],
            ['Support tube or T34 simple', 1, 1, null],
            ['tack 10 double', 2, 2, null],
            ['TALOCHE GOMME GM', 2, 2, null],
            ['taloche gomme PM', 2, 2, null],
            ['TALOCHE PLASTIQUE', 2, 2, null],
            ['tayou railli 18 super', 1, 1, null],
            ['jeux de lame t111c briko sisouteuse (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['tayou gaz', 1, 1, null],
            ['tayou gaz 6/12 anas', 2, 2, null],
            ['tayou super uni', 1, 1, null],
            ['tayou raylli', 0, 0, null],
            ['tenaille acem extra', 8, 8, null],
            ['vis th 22x50 8,8 noir 2éme main', 2, 2, null],
            ['vis th 22x50 8,8 noir', 1, 1, null],
            ['tirphon 10x50', 0, 0, null],
            ['Tirfond 10x80', 0, 0, null],
            ['Tirfond zingue 6x70', 0, 0, null],
            ['tirphon 8x70', 0, 0, null],
            ['meche 12 tita', 4, 4, null],
            ['TIRPHON 6X60', 0, 0, null],
            ['tirphon 6x80', 0, 0, null],
            ['tirphon 8x40', 0, 0, null],
            ['tirphon 8x50', 0, 0, null],
            ['tirphon 6x80 np', 0, 0, null],
            ['toil isolant couleur+noir pm', 0, 0, null],
            ['console lavabo ayedi (omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['peton fermé 4x40 (omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['tournevis acem 6x125', 2, 2, null],
            ['tournevis ph1 x100 acem', 1, 1, null],
            ['tournevis ph2 x200 acem', 3, 3, null],
            ['truelle 18 acem', 5, 5, null],
            ['bidon top latex 5l', 32, 32, null],
            ['tube graisse', 2, 2, null],
            ['tube silcone blanc universail GP', 5, 5, null],
            ['tube silicone blanc sibax acrylique ls 24', 2, 2, null],
            ['tube silicone transparent sibax', 8, 8, null],
            ['vis th 14x120', 1, 1, null],
            ['vis 3,5x16 jaune', 0, 0, null],
            ['vis th 10x30', 0, 0, null],
            ['tirfon 6x50', 0, 0, null],
            ['peton fermé 6x40', 0, 0, null],
            ['vis th 12x100', 1, 1, null],
            ['vis 5x40 jaune', 0, 0, null],
            ['tube gm colle pentagit (pentacol)', 2, 2, null],
            ['tube colle pentagit 35g (pentacol)', 1, 1, null],
            ['VIS Th 8x50 nprix', 0, 0, null],
            ['vis th 14x50 8,8 noir', 1, 1, null],
            ['vis th 10x40 8,8 noir', 0, 0, null],
            ['vis th 10x50', 0, 0, null],
            ['vis th 10x60', 0, 0, null],
            ['vis th 12x50 galv', 0, 0, null],
            ['VIS TH 12X70', 0, 0, null],
            ['vis th 12x40 8,8 noir', 0, 0, null],
            ['vis assemblage 5x50', 0, 0, null],
            ['boulon 10x40 np gal', 0, 0, null],
            ['VIS TH 10x60 8,8 galv', 0, 0, null],
            ['VIS TH 14x80 8,8 galv', 1, 1, null],
            ['VIS TH 16X70', 1, 1, null],
            ['VIS TH 16X80', 1, 1, null],
            ['vis th 6x20', 0, 0, null],
            ['vis th 6x30', 0, 0, null],
            ['vis th 6x40', 0, 0, null],
            ['vis th 6x50', 0, 0, null],
            ['vis th 6x60', 0, 0, null],
            ['vis th 8x30', 0, 0, null],
            ['vis th 8x40', 0, 0, null],
            ['vis th 8x100 4,8 galv', 0, 0, null],
            ['tirphon 6x40', 0, 0, null],
            ['vis th 6x70', 0, 0, null],
            ['peton fermé 5x30 (besbes)', 0, 0, null],
            ['vis th 8x20', 0, 0, null],
            ['ecrou 22 galv np', 1, 1, null],
            ['vis th 14x60 8,8 noir', 1, 1, null],
            ['vis th 10x100', 0, 0, null],
            ['Disque tranc 350', 12, 12, null],
            ['Dique a lamelle 115 Z80', 3, 3, null],
            ['meche sds 10x160', 2, 2, null],
            ['vis à bois 5x30 jaune', 0, 0, null],
            ['tube silicone blanc acrylique sibax', 2, 2, null],
            ['Pompe mousse 600g 750ml (EEc)', 8, 8, null],
            ['boite colle blanc 1kg Brima', 5, 5, null],
            ['boite colle blanc 400g Brima', 3, 3, null],
            ['vanne conique 1/2', 14, 14, null],
            ['kg pointe tp100 sid', 4, 4, null],
            ['kg pointe tp120 +150 sid', 4, 4, null],
            ['kg pointe tp 20 sid', 5, 5, null],
            ['vanne a visser 16', 16, 16, null],
            ['Ecrou 22 noir', 1, 1, null],
            ['serre cable galv 8 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['skotch d\'emballage marron', 1, 1, null],
            ['skotch d\'emballage transparent', 1, 1, null],
            ['rondelle 8x22x2,5', 0, 0, null],
            ['cartouche mini antigoute (naim)', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['boite sotumail 1kg blanc', 9, 9, null],
            ['pinceau rond n 6 cristal (omar)', 7, 7, $suppliers['Omar Abdelkefi'] ?? null],
            ['Serrure encastré noir rev 22 MTS (EBH)', 6, 6, null],
            ['Evier Inox 120x60 2B+S', 181, 181, null],
            ['flexible de douche tresse lux plast (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['Tuyau arrosage renf 15 AS', 1, 1, null],
            ['Equerre 80x80', 0, 0, null],
            ['Bidon duliant 4l Normal', 18, 18, null],
            ['Duliant super extra 1l', 8, 8, null],
            ['Clé mal 4mm Acem', 1, 1, null],
            ['Tournivis en T a poigné mal 6 pont 3mm', 5, 5, null],
            ['Enduit Fleurtex 1kg', 3, 3, null],
            ['disque acier 230 (EBH)', 3, 3, null],
            ['robinet equerre conique (monji)', 9, 9, $suppliers['Monji ben Hamed'] ?? null],
            ['brosse metalique avec manche (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['Tube colle Tangite 125g Henkel (omar)', 7, 7, $suppliers['Omar Abdelkefi'] ?? null],
            ['Raccord à visser 16x1/2 F Amecap', 4, 4, null],
            ['Clé mal 3mm courte Sumex', 0, 0, null],
            ['Rivet 3,8x12', 0, 0, null],
            ['Brosse metallique plastique N/5', 3, 3, null],
            ['disque acier 115 (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['moteur dap 0,4 ch', 175, 175, null],
            ['abrasif 220', 1, 1, null],
            ['paquet super hydrofyge (omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['Siphon de cours plastique 20x20', 5, 5, null],
            ['Siphon de cours plastique 15x15', 2, 2, null],
            ['Grille d\'aération dim 200', 2, 2, null],
            ['Grille d\'aération carrée 25x25', 4, 4, null],
            ['siphon cours 10 ( had )', 1, 1, null],
            ['Tube colle tangit 125g (monji)', 7, 7, $suppliers['Monji ben Hamed'] ?? null],
            ['tube colle tangit 50g (Omar )', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['disque pierre 115 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['melangeur 2 tige Sopal', 3, 3, null],
            ['Robinet flotteur Ejim', 5, 5, null],
            ['vis tr 5x40 galv (Omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['Gand a vis 4,7/50', 0, 0, null],
            ['Gand a vis 5,8/70', 0, 0, null],
            ['Rondelle 8x27x2,5', 0, 0, null],
            ['Rondelle 6x18 (brahim)', 0, 0, null],
            ['Rondelle 8x18 (brahim)', 0, 0, null],
            ['Pelle 27 Orange Acem', 11, 11, null],
            ['Pelle 29 Orange Acem', 12, 12, null],
            ['Jeux fixation chauffe bain', 2, 2, null],
            ['boite sotumail 1kg noire+jaune+vert (omar)', 9, 9, $suppliers['Omar Abdelkefi'] ?? null],
            ['boite sotumat 1kg blanc', 7, 7, null],
            ['Paumelle BP 140x2,5 nicklé satiné D', 4, 4, null],
            ['Paumelle BP 140x2,5 nicklé satiné G', 4, 4, null],
            ['Pioche a pic king (omar)', 21, 21, $suppliers['Omar Abdelkefi'] ?? null],
            ['collier galv 125 (ayedi sanitaire)', 1, 1, $suppliers['Ramzi Ayedi'] ?? null],
            ['Kg pointe tp 60', 4, 4, null],
            ['Boite hirondelle 1kg blanc', 6, 6, null],
            ['pince coupante Acem', 11, 11, null],
            ['Seau colle blanche Brima 4kg', 13, 13, null],
            ['robinet equerre 1/2-16 Amecap (monji)', 12, 12, $suppliers['Monji ben Hamed'] ?? null],
            ['Rosace a visser 1/2 F (monji)', 10, 10, $suppliers['Monji ben Hamed'] ?? null],
            ['Boite colle neoprene 200 ml tunisie colle (EBH)', 4, 4, null],
            ['Ceroc poudre etanche', 4, 4, null],
            ['Disque acier 125 (EBH)', 1, 1, null],
            ['Disque pierre 125 (EBH)', 2, 2, null],
            ['Porte visite 30/30 plastique blanc', 3, 3, null],
            ['Porte visite 25/40 plastique blanc', 3, 3, null],
            ['Collier multicouche double 16 avec tirfon', 0, 0, null],
            ['bobine n18 (ahmed )', 2, 2, $suppliers['Ahmed'] ?? null],
            ['bobine n36 (ahmed)', 2, 2, $suppliers['Ahmed'] ?? null],
            ['manche pioche olivier', 2, 2, null],
            ['Vis TH 8x30 galv', 0, 0, null],
            ['Rivet 4,8x20', 0, 0, null],
            ['Raccord à visser 16x1/2 M Sopal', 5, 5, null],
            ['Te à visser 16x16x16 Sopal', 11, 11, null],
            ['Bonde a vis 33 Ejim (ben hamed)', 4, 4, null],
            ['Collection 5p à miroir oval blanc+bleu (monji)', 34, 34, $suppliers['Monji ben Hamed'] ?? null],
            ['Flexible melangeur 12 sanitaire', 4, 4, null],
            ['Flexible melangeur 15 sanitaire', 4, 4, null],
            ['Coude PVC 32 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['Coude PVC 40 (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['Coude PVC 63', 2, 2, null],
            ['Kg Point TP 60+70+10+12+15 SID (EBH)', 4, 4, null],
            ['Rivet 3,8x20', 0, 0, null],
            ['Rivet 4,8x18', 0, 0, null],
            ['Console lavabo 52', 6, 6, null],
            ['Grille d\'aération 100', 1, 1, null],
            ['Grille d\'aération 125', 1, 1, null],
            ['Kg pointe Tp 100 SGT', 4, 4, null],
            ['Kg pointe Tp 70 SGT', 4, 4, null],
            ['Support moteur plastique(Omar)', 6, 6, $suppliers['Omar Abdelkefi'] ?? null],
            ['tube silicone blanc+gris acrylique Somafix(omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['Flexible raccordement 12/12 F-F (omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['Siphon plastique 20x20 (Ramzi Ayedi)', 5, 5, $suppliers['Ramzi Ayedi'] ?? null],
            ['jeux Scie à cloche 6 pièces (Euro Equipement)', 8, 8, $suppliers['Euro Equipement'] ?? null],
            ['Reduction colerette 26x15 jaune Amecap', 6, 6, null],
            ['Reduction colerette 26x20 jaune Amecap', 5, 5, null],
            ['Reduction spécial 26x15 jaune Amecap', 6, 6, null],
            ['Reduction spécial 20x15 jaune Amecap', 4, 4, null],
            ['vis tr 5x50 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['vis tr 5x30 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['vis tr 4x50 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['racloir omsa (monj)', 2, 2, null],
            ['boite rexim 1kg', 6, 6, null],
            ['cartouche 3/8 salakta rond', 4, 4, null],
            ['press contrôle prima', 43, 43, null],
            ['Tube IPALPEX 16x2mm (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['meche 12 diager (monji)', 5, 5, $suppliers['Monji ben Hamed'] ?? null],
            ['Meche inox 5mm', 2, 2, null],
            ['Raccord a visser 16x1/2 f Sopal', 5, 5, null],
            ['Rouleau Havan 40x48 transparent+marron (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['Riv bloc KUMRU PT (omar)', 10, 10, $suppliers['Omar Abdelkefi'] ?? null],
            ['vis th 12 x140 8,8 galv avec ecrou', 1, 1, null],
            ['Seau colle blanche 4kg (Brima colle)', 15, 15, null],
            ['Boite colle blanche 400g (Brima colle)', 2, 2, null],
            ['Boite colle blanche 700g (Brima colle)', 3, 3, null],
            ['Boite colle neoprene 750g (Brima colle)', 9, 9, null],
            ['Tube Neoprane 703 (Brima colle)', 3, 3, null],
            ['Coulier multicouche 14 sans tirphon', 0, 0, null],
            ['Coulier multicouche 16 avec couvercle', 0, 0, null],
            ['manchon bargataire droit 25', 2, 2, null],
            ['Pompe retouche noir brillant+mat 400 ml (Omar Abdelkefi)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['reduction pvc 63/50 (Omar Abdelkefi)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['Coude PVC 40/90°Socyp (Omar Abdelkefi)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['Collier galv 80 complet (Ramzi Ayedi)', 1, 1, $suppliers['Ramzi Ayedi'] ?? null],
            ['coude pvc 40x45 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['ecrou 4 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['Disque lamelles 115 Inox Z80 Lamelflex (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['lame de scie a meteaux omsa (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['gond a vis 4,7x50 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['porte verre abs lux plast (EBH)', 5, 5, null],
            ['Coude PVC 80/90 (EBH)', 2, 2, null],
            ['flexible raccord 12*15 f/f 30 cm (monji)', 4, 4, $suppliers['Monji ben Hamed'] ?? null],
            ['Manchon galvanisé 20x27 DD (EBH)', 2, 2, null],
            ['arret de porte plastique tic tac (EBH)', 0, 0, null],
            ['Mamelon galvanisé 20x27 (EBH)', 2, 2, null],
            ['lame de scie a meteaux omsa (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['antrouille 5 kg gris soutinol', 23, 23, null],
            ['boite laqué fleurtex 1 k blanc', 12, 12, null],
            ['culotte pvc 100 socyp', 4, 4, null],
            ['te pvc 32', 0, 0, null],
            ['colle mdf 200 ml (omar)', 6, 6, $suppliers['Omar Abdelkefi'] ?? null],
            ['reduction pvc 100/40 socyp', 2, 2, null],
            ['reduction pvc 100/63 socyp', 2, 2, null],
            ['reduction pvc 50/40 socyp', 0, 0, null],
            ['reduction pvc 63/40 socyp', 1, 1, null],
            ['kg pointe tp 50 sid', 4, 4, null],
            ['mélangeur lavabo salakta', 79, 79, null],
            ['mélangeur evier salakta', 79, 79, null],
            ['métre tube multicouche 16', 2, 2, null],
            ['Tube Pvc 100x1,8 MTMB', 20, 20, null],
            ['Kg pointe TV 20 SID', 6, 6, null],
            ['reduction pvc 63x40 (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['Flexible toilette blanc Ejim (monji)', 4, 4, $suppliers['Monji ben Hamed'] ?? null],
            ['collection 5 pieces blanc (Ramzi Ayedi)', 20, 20, $suppliers['Ramzi Ayedi'] ?? null],
            ['près cadre 30x30', 0, 0, null],
            ['près cadre 40x80', 0, 0, null],
            ['equerre 50x50', 0, 0, null],
            ['vis a bois 5x70 blanc+jaune', 0, 0, null],
            ['vis a bois 4x40 jaune', 0, 0, null],
            ['meche 4 cobalt (eec)', 1, 1, null],
            ['meche 6 cobalt (eec)', 3, 3, null],
            ['kg fil d\' attache (ahmed)', 4, 4, $suppliers['Ahmed'] ?? null],
            ['huil d\'impression 0,9l Sotunol', 10, 10, null],
            ['huil de lin 0,9l Sotunol', 13, 13, null],
            ['fourche 4 dents brico (monji)', 13, 13, $suppliers['Monji ben Hamed'] ?? null],
            ['métre tube gorge 25 bleu proplast (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['coude pvc 100 (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['tube gorge 32 rouge', 0, 0, null],
            ['Rondelle 12x44', 0, 0, null],
            ['Siphon de cours plastique 15 avec coude (had)', 3, 3, null],
            ['Grille d\'aeration 160', 2, 2, null],
            ['Grille d\'aeration 140', 1, 1, null],
            ['Kg pointe TP 40 SID (Omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['Boite Sotumail 500g noir', 5, 5, null],
            ['Boite Sotumail 500g blanc', 6, 6, null],
            ['Papier abrasif 120', 1, 1, null],
            ['Coude PVC 80/90 Socyp (Omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['Coude PVC 50/45° Socyp (Omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['Coude PVC 63/45° Socyp (Omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['Coude PVC 100/45° Socyp (Omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['Coude PVC 32/90° Socyp (Omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['Coude PVC 40/90° Socyp (Omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['Coude PVC 50/90° Socyp (Omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['Coude PVC 100/90° Socyp (Omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['rosace a visser 3/4 m (monji)', 17, 17, $suppliers['Monji ben Hamed'] ?? null],
            ['Caniveau de douche Slim CAR 300 Ejim', 27, 27, null],
            ['Caniveau de douche Slim CAR 400 Ejim', 32, 32, null],
            ['Siphon Exten 33 Ejim', 2, 2, null],
            ['Siphon Exten 33 Lux Plast', 2, 2, null],
            ['Siphon Exten 40 Ejim', 3, 3, null],
            ['Siphon Exten 40 Lux Plast', 2, 2, null],
            ['Te de vidage a trop plein Ejim', 18, 18, null],
            ['Te de vidage bi-bac Ejim', 16, 16, null],
            ['perche (Naim)', 6, 6, $suppliers['Naim Makni'] ?? null],
            ['film attirable 2,4 kg (massmoudi)', 16, 16, null],
            ['tayou cristal 8 (EBH)', 1, 1, null],
            ['boite colle neoprene 750g sif colle 804 ( EBH)', 11, 11, null],
            ['plomb de macon 800g imp (monji)', 7, 7, $suppliers['Monji ben Hamed'] ?? null],
            ['pistolet silicone pls rouje (monji)', 4, 4, $suppliers['Monji ben Hamed'] ?? null],
            ['rivet 4x16 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['metre moustiquere 1,2 bleu (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['disque inox 125/1mm monji)', 1, 1, null],
            ['boite colle neoprene 750 ml cn 715 tunisie cole( monji)', 10, 10, $suppliers['Monji ben Hamed'] ?? null],
            ['tube colle tangit 50g (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['collection 5 pcs blanc+bleu (omar)', 34, 34, $suppliers['Omar Abdelkefi'] ?? null],
            ['pompe retouche chrommé (omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['boite laqué blanc soutinol 4 kg ( omar)', 35, 35, $suppliers['Omar Abdelkefi'] ?? null],
            ['pinceau radiateur 50 (omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['jeux de fixation mécanisme réservoir de chasse (omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['kg corde ficelle sbewli (omar)', 8, 8, $suppliers['Omar Abdelkefi'] ?? null],
            ['cartouche mélangeur rond amecap (monji)', 5, 5, $suppliers['Monji ben Hamed'] ?? null],
            ['collier 26 sico (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['agraffe 14 (ebh)', 13, 13, null],
            ['bande avis 33 lux plast (ebh)', 3, 3, null],
            ['coude 16 1/2 F à visser ecrou libre (EBH)', 8, 8, null],
            ['coude 16 3/4 F à visser ecrou libre (EBH)', 9, 9, null],
            ['Mitigeur evier Douz', 175, 175, null],
            ['Mitigeur lavabo Douz', 147, 147, null],
            ['Mitigeur douche Douz', 184, 184, null],
            ['Mitigeur lavabo Kerkennah', 96, 96, null],
            ['console etagere 100x75 amig (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['Mitigeur douche Djerba', 123, 123, null],
            ['Mitigeur evier Djerba', 141, 141, null],
            ['console etagere 150x125 amig (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['Raccord mélangeur 12 (EBH)', 5, 5, null],
            ['Robinet toilette Salakta', 17, 17, null],
            ['Pompe retouche blanc brillant + mat400 ml (Omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['Pompe retouche rouge 400 ml (Omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['Pompe retouche dore metalise 400 ml (Omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['Boite antrouille 1Kg gris Sotunol (Omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['Kg pointe tp 70 SID (Omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['Cartouche mini laqué Cristal (EBH)', 1, 1, null],
            ['kg pointe tv 40 SID (omar)', 6, 6, $suppliers['Omar Abdelkefi'] ?? null],
            ['moteur 0,5 total ( omar)', 112, 112, $suppliers['Omar Abdelkefi'] ?? null],
            ['masette catchou (omar)', 6, 6, $suppliers['Omar Abdelkefi'] ?? null],
            ['consol étagére 150x200 normal GK (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['consol étagére 200x250 normal GK (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['consol étagére 250x300 normal GK (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['antirouille 500g gris soutinol (omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['collier galvaniser 125 sibec (omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['coude a visser 16*1/2 f sop (monji', 6, 6, null],
            ['raccord 1/2 f conioque (monji', 3, 3, null],
            ['jeux de meche 4 boch (monji', 8, 8, null],
            ['jeux de meche 6 boch (monji', 14, 14, null],
            ['collier ser 8-13 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['pioche a pic import 2 kg (monji)', 22, 22, $suppliers['Monji ben Hamed'] ?? null],
            ['scie à métaux brico (monji)', 8, 8, $suppliers['Monji ben Hamed'] ?? null],
            ['sabot de meuble 85 lux plast (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['monchon a visser 16 (monji)', 7, 7, $suppliers['Monji ben Hamed'] ?? null],
            ['raccord a visser 16*3/8 f sop ( monji)', 5, 5, $suppliers['Monji ben Hamed'] ?? null],
            ['bouchon bleu tube pex 16 had', 0, 0, null],
            ['canniveau 50 (ayedi sanitaire)', 30, 30, $suppliers['Ramzi Ayedi'] ?? null],
            ['canniveau 60 (ayedi sanitaire)', 32, 32, $suppliers['Ramzi Ayedi'] ?? null],
            ['Vis d\'assemblage 5x50 pointu (Euro Equipement)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['verreau box 8cm (Brahim)', 0, 0, null],
            ['verreau box 10cm (Brahim)', 1, 1, null],
            ['kg pointe tp 30 sid', 5, 5, null],
            ['cheville de 6 HAD', 0, 0, null],
            ['boule tube t34 dorré', 1, 1, null],
            ['canniveau 40 (ayedi sanitaire)', 28, 28, $suppliers['Ramzi Ayedi'] ?? null],
            ['tube silicone noire gp ( omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['charnière fixe 90 jaune( brahim)', 0, 0, null],
            ['peton fermé 6x70', 0, 0, null],
            ['boite colle tangit 500g ( ben hamed)', 22, 22, null],
            ['siphon lavabo 33 ejim (ben hamed)', 3, 3, null],
            ['siphon evier 40 ejim (ben hamed)', 3, 3, null],
            ['bande a vis 40 ejim (ebh)', 5, 5, null],
            ['verroux mts tico (ben hamed)', 22, 22, null],
            ['meche 8 diager (ben hamed)', 2, 2, null],
            ['meche 10 diager (ben hamed)', 3, 3, null],
            ['siphon lavabo 33 lux plast (ben hamed)', 2, 2, null],
            ['raccord a visser 16x3/4 f Sopal (ben hamed)', 6, 6, null],
            ['raccord a visser 16x3/4 M Sopal (ben hamed)', 5, 5, null],
            ['raccord a visser 20x3/4 m sopal (ben hamed)', 8, 8, null],
            ['ecrou 6 ( ben hamed)', 0, 0, null],
            ['vis 4x50 ( ben hamed)', 0, 0, null],
            ['abrasif 150 (ben hamed) MA', 1, 1, null],
            ['crochet nylon blanc 40mm GM', 0, 0, null],
            ['balai contonner cristal (ben hamed)', 4, 4, null],
            ['equerre 18x18 brahim', 0, 0, null],
            ['coude pvc 63/45 (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['rouleau bande isolant 10/80 noir (Omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['metre tube gorge 16 rouge PROPLAST (Omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['metre tube gorge 16 bleu PROPLAST (Omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['Kg brazure 3 imp (Omar)', 57, 57, $suppliers['Omar Abdelkefi'] ?? null],
            ['Coude PVC 63/90 SOCYP (Omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['meche sds plus 16x400mm (Euro Equipement)', 7, 7, $suppliers['Euro Equipement'] ?? null],
            ['meche sds plus 16x600mm (Euro Equipement)', 11, 11, $suppliers['Euro Equipement'] ?? null],
            ['papier abrasif 180 guepard (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['boite graisse 400g (monji)', 5, 5, $suppliers['Monji ben Hamed'] ?? null],
            ['boite colle tangit 250 g (monji)', 12, 12, $suppliers['Monji ben Hamed'] ?? null],
            ['brosse plafonner pm (naim)', 2, 2, $suppliers['Naim Makni'] ?? null],
            ['charniere fixe 90 (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['bande trop plein ejim (ben hamed)', 13, 13, null],
            ['collier 32 sicovis (ben hamed)', 0, 0, null],
            ['support climatiseur', 12, 12, null],
            ['prét cadre 40x40', 0, 0, null],
            ['rouleau papier coulant 20x30 (Omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['Raccord a vissé 16x1/2 M SIMEP (Omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['Raccord a vissé 16x1/2 F SIMEP (Omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['Raccord a vissé 16x3/8 M SIMEP (Omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['Robinet equerre a vissé (Omar)', 9, 9, $suppliers['Omar Abdelkefi'] ?? null],
            ['jeux patin anti vibration pm (Omar)', 9, 9, $suppliers['Omar Abdelkefi'] ?? null],
            ['Bonde a vis 40 lux plast (ben hamed)', 3, 3, null],
            ['Flexible toilette blanc tresse lux plast (EBH)', 4, 4, null],
            ['Kit siphon machine a laver Ejim (EBH)', 4, 4, null],
            ['Pinceau rond n6 2eme choix Cristal (EBH)', 4, 4, null],
            ['Robinet flotteur alimantation bas (EBH)', 8, 8, null],
            ['Rouleau papier abrasif 60x18x25 noir (EBH)', 43, 43, null],
            ['rouleau antigo cristal (EBH)', 7, 7, null],
            ['boite graisse 800g (EBH)', 8, 8, null],
            ['Té de vidage avec trop plein lux plast (EBH)', 14, 14, null],
            ['Disque carbure 150', 6, 6, null],
            ['Disque diamant turbo 125', 7, 7, null],
            ['Disque diamant turbo 230', 20, 20, null],
            ['siphon cours 25 ( had )', 6, 6, null],
            ['Boite 250g neoprene (Brima Colle)', 4, 4, null],
            ['burin pointu acem 250 (omar)', 6, 6, $suppliers['Omar Abdelkefi'] ?? null],
            ['te barg 25x25x25 ( omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['rouleau scotch d emballage 48/70 (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['te bargataire 25x1/2m (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['rouleau bande isolant 10/80 blanc (Omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['rouleau chautreton noir ( omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['rouleau chautreton blanc ( omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['monchon a visser 16 (omar)', 6, 6, $suppliers['Omar Abdelkefi'] ?? null],
            ['boite graisse 800g (omar)', 8, 8, $suppliers['Omar Abdelkefi'] ?? null],
            ['rouleau papier crepe 48x25 (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['disque tranc 115x1mm inox boch (ebh)', 1, 1, null],
            ['loqueteau a pompe (ebh)', 1, 1, null],
            ['vis a bois 4x40 jaune (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['siphon extensible 33 ejim (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['starmetal (monji)', 6, 6, $suppliers['Monji ben Hamed'] ?? null],
            ['siphon orientable 15 inox ejim (monj)', 14, 14, null],
            ['canniveau slim ejim 50 (monji)', 33, 33, $suppliers['Monji ben Hamed'] ?? null],
            ['tayou cristal 16 (sicoplast)', 1, 1, null],
            ['reduction pvc 40/32', 0, 0, null],
            ['grillle d\'ailleration 100 (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['gand a vis 4x50 (omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['gand a vis 5,8x60 (omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['metre mouSTIQUERE 1,2 (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['bagette faience pvc couleur (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['volant robinet toilette salakta (monji)', 7, 7, $suppliers['Monji ben Hamed'] ?? null],
            ['roulette ravallement cristal (monji)', 6, 6, $suppliers['Monji ben Hamed'] ?? null],
            ['rouleau abrasif 40x16x25 rouje (monji)', 40, 40, $suppliers['Monji ben Hamed'] ?? null],
            ['tayou cristal 8 bleu (ahmed)', 1, 1, $suppliers['Ahmed'] ?? null],
            ['cheville de 8 HAD (ahmed)', 0, 0, $suppliers['Ahmed'] ?? null],
            ['disque 115 x 1mm inox mhirsi (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['bobine etain 1,5 mm (monji)', 23, 23, $suppliers['Monji ben Hamed'] ?? null],
            ['ventouse 102 (omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['bobine n 36 (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['rouleau abrasif noire 80x16x25 (monji)', 49, 49, $suppliers['Monji ben Hamed'] ?? null],
            ['console etagere 300x350 amig (omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['riv bloc KUMRU PT (ahmed) ns', 11, 11, $suppliers['Ahmed'] ?? null],
            ['support profilé 30 cm (ahmed) had', 7, 7, $suppliers['Ahmed'] ?? null],
            ['support profilé 40 cm (ahmed) had', 8, 8, $suppliers['Ahmed'] ?? null],
            ['support profilé 50 cm (ahmed) had', 9, 9, $suppliers['Ahmed'] ?? null],
            ['métre tayou cristal 6 sicoplast (ahmed)', 0, 0, $suppliers['Ahmed'] ?? null],
            ['vis th 8x70', 0, 0, null],
            ['vis autoperceuse 6,3x120', 0, 0, null],
            ['seau de maçon orangé (omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['cheville 10 had (omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['reduction pvc 100/50 (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['vis tr 4x20 (omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['serrure encastré rev 22 (mts)', 6, 6, null],
            ['serrure encastré c22 (mts)', 6, 6, null],
            ['serrure encastré b40 (mts)', 16, 16, null],
            ['blocus tico 140 (amal)', 27, 27, null],
            ['blocus tico 140 (mts)', 27, 27, null],
            ['vis 4x60 (ahmed)', 0, 0, $suppliers['Ahmed'] ?? null],
            ['tayou cristal 8 sicoplast (ahmed)', 0, 0, $suppliers['Ahmed'] ?? null],
            ['tayou cristal 10 sicoplast (ahmed)', 1, 1, $suppliers['Ahmed'] ?? null],
            ['ecrou 12 ( ben hamed)', 0, 0, null],
            ['paire verroux bronze emm (monji)', 14, 14, $suppliers['Monji ben Hamed'] ?? null],
            ['attache lavabo (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['reduction pvc 80x50 imp (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['pinceau 70 cristal (monji)', 5, 5, $suppliers['Monji ben Hamed'] ?? null],
            ['boulon tr 4x20 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['melangeur douche salakta (monji)', 69, 69, $suppliers['Monji ben Hamed'] ?? null],
            ['boulon tr 5x20 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['fixation de bidet inox had (ahmed)', 2, 2, $suppliers['Ahmed'] ?? null],
            ['papier abrasif 180 guepard (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['abattant socype (omar)', 10, 10, $suppliers['Omar Abdelkefi'] ?? null],
            ['manche de pioche (omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['bouchon pvc 125 (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['disque pierre 230 (laila)', 5, 5, null],
            ['disque acier 230 (laila)', 3, 3, null],
            ['corde linge 10m (Amal)', 1, 1, null],
            ['corde linge 15m (Amal)', 1, 1, null],
            ['Flexible toilette blanc tres lux plast (Amal)', 3, 3, null],
            ['Pinceau 20 carthago (Amal)', 1, 1, null],
            ['Pinceau 30 carthago (Amal)', 1, 1, null],
            ['Pinceau 60 carthago (Amal)', 2, 2, null],
            ['Pinceau 70 carthago (Amal)', 2, 2, null],
            ['rouleau film attirable (Amal)', 15, 15, null],
            ['charniere invisible 1,5cm importé (Ahmed)', 1, 1, $suppliers['Ahmed'] ?? null],
            ['bobine fil de macon 36 (amal)', 2, 2, null],
            ['bobine fil de macon 18 (amal)', 2, 2, null],
            ['rouleau abrasif 40x18x25 rouje (monji)', 44, 44, $suppliers['Monji ben Hamed'] ?? null],
            ['coude barg 25x25 (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['teinte marron+jaune citron+noir 100 g soutinol (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['kg castolin platex (omar)', 70, 70, $suppliers['Omar Abdelkefi'] ?? null],
            ['moteur dap 0,4 ch (omar)', 188, 188, $suppliers['Omar Abdelkefi'] ?? null],
            ['press control rinoh (omar)', 45, 45, $suppliers['Omar Abdelkefi'] ?? null],
            ['abattant ( lux plast)', 8, 8, null],
            ['siphon lavabo 33 ( lux plast )', 2, 2, null],
            ['flexible toilette pvc ( lux plast)', 2, 2, null],
            ['patins anti-vibration pm (monji)', 10, 10, $suppliers['Monji ben Hamed'] ?? null],
            ['bac stockage n 4 (monji)', 8, 8, $suppliers['Monji ben Hamed'] ?? null],
            ['siphon evier 40 lux plast (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['charniere abattant ejim (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['Abattant toilette (ayedi sanitaire)', 8, 8, $suppliers['Ramzi Ayedi'] ?? null],
            ['coude pvc 125/45 SOCYP (Omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['culotte pvc 125 SOCYP (Omar)', 6, 6, $suppliers['Omar Abdelkefi'] ?? null],
            ['kg pointe tp 60 SID (Omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['culotte pvc 40 (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['rivet aluminium 4x16 (Omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['tick tack plastique', 0, 0, null],
            ['vis a bois 4x16 jaune', 0, 0, null],
            ['rivet 3,8x18', 0, 0, null],
            ['Flexible raccordement 15x15 MF (EBH)', 4, 4, null],
            ['pipe de toilette coudée ejim (monji)', 5, 5, $suppliers['Monji ben Hamed'] ?? null],
            ['coude pvc 50 (ebh)', 1, 1, null],
            ['coude pvc 75 (ebh)', 2, 2, null],
            ['culotte pvc 32 (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['tige cremoune normale jaune', 2, 2, null],
            ['abattant lux plast (monji)', 9, 9, $suppliers['Monji ben Hamed'] ?? null],
            ['palette denté 27x12 galv mariem plast (monji)', 5, 5, $suppliers['Monji ben Hamed'] ?? null],
            ['chasse d\'eau poussoir lateral blanc ejim commer beta(monji', 41, 41, null],
            ['tournet n 7 zingue (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['boule tube t27 dorré', 1, 1, null],
            ['canniveau de douche slim 70 (monji)', 31, 31, $suppliers['Monji ben Hamed'] ?? null],
            ['ciseaux a bois 14 m plastic imp (monji)', 7, 7, $suppliers['Monji ben Hamed'] ?? null],
            ['siphon d\' angle inox ejim (monji)', 22, 22, $suppliers['Monji ben Hamed'] ?? null],
            ['monture scie briko simple s03013001 (monji)', 8, 8, $suppliers['Monji ben Hamed'] ?? null],
            ['canniveau de douche slim 60 (monji)', 29, 29, $suppliers['Monji ben Hamed'] ?? null],
            ['culotte pvc 63 (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['téte robiet jardin 15/21 (omar)', 7, 7, $suppliers['Omar Abdelkefi'] ?? null],
            ['joint partaire 1mm de machine', 0, 0, null],
            ['vis téte sipon 5x50 (clé 5 sipon)', 0, 0, null],
            ['riv bloc siam PT (ahmed) bronze', 21, 21, $suppliers['Ahmed'] ?? null],
            ['fixation 1 tige k2s( monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['papier abrasif 400 guepard (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['clapet york 1/2 15*21 (monji)', 12, 12, $suppliers['Monji ben Hamed'] ?? null],
            ['pomme de douche ejim (monji)', 8, 8, $suppliers['Monji ben Hamed'] ?? null],
            ['raccord a visser 16x3/4 m amecap (ben hamed)', 5, 5, null],
            ['pompe retouche gris+vert +bleu(omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['tube teinte surfacer noir fleurtex (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['tube teinte surfacer créme fleurtex (omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['tube teinte surfacer marron fleurtex (omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['charnière 11 florida (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['cremoune anneau petra bronze (monji)', 15, 15, $suppliers['Monji ben Hamed'] ?? null],
            ['decapant 3x1 (monji)', 4, 4, $suppliers['Monji ben Hamed'] ?? null],
            ['detendeur gaz 28 (monji)', 12, 12, $suppliers['Monji ben Hamed'] ?? null],
            ['derbicote 5 kg (monji)', 22, 22, $suppliers['Monji ben Hamed'] ?? null],
            ['te pvc 63 socype (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['te pvc 40 socype (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['teinte surfacer couleur flash (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['boite decapant 1l khoutaf (omar)', 4, 4, $suppliers['Omar Abdelkefi'] ?? null],
            ['brosse metalique avec manche (omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['couteau mastic 75/70 mb (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['detendeur gaz 37 mondial italy (monji)', 12, 12, $suppliers['Monji ben Hamed'] ?? null],
            ['equerre plat 100 (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['plomb de macon 600g famm (omar)', 6, 6, $suppliers['Omar Abdelkefi'] ?? null],
            ['support cartouche laqué (naim makni)', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['support profilé 20 had (ahmed)', 6, 6, $suppliers['Ahmed'] ?? null],
            ['collier serrage 16-23 (eee)', 0, 0, null],
            ['collier serrage 13-19 (eee)', 0, 0, null],
            ['collier serrage 18-25 (eee)', 0, 0, null],
            ['raccord de compteur bargataire 25 /3/4 mal sopal', 6, 6, null],
            ['boite argent 500 gr fleurteux', 10, 10, null],
            ['rondelle 14x30', 0, 0, null],
            ['support climatiseur 24 mille', 16, 16, null],
            ['coude a sertir 16*1/2 f sopal (monji)', 6, 6, $suppliers['Monji ben Hamed'] ?? null],
            ['verroux box de 8 (ben hamed)', 1, 1, null],
            ['verroux box de 12 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['métre bargataire 25 1er choix (sicoplast)', 1, 1, null],
            ['métre bargataire 25 2eme choix (sicoplast)', 1, 1, null],
            ['métre moustiquerre 1,2 (hichem caisse eechéque)', 2, 2, $suppliers['Euro Equipement'] ?? null],
            ['métre grillage fibre 50 (hichem caisse eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['charniere invi courte (naim makni)', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['collier az 32 sico (omar)', 0, 0, $suppliers['Omar Abdelkefi'] ?? null],
            ['kg castolin', 69, 69, null],
            ['métre tube rond 34 dorré', 6, 6, null],
            ['pinceau rond n 6 cristal (monji)', 7, 7, $suppliers['Monji ben Hamed'] ?? null],
            ['bonde lavabo 33 tige inox lux plast (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['tube rideau argent 27 (monji)', 33, 33, $suppliers['Monji ben Hamed'] ?? null],
            ['scie jardin hannibal (monji)', 17, 17, $suppliers['Monji ben Hamed'] ?? null],
            ['robinet jardin jaune sop téte plastique 15 (monji)', 15, 15, $suppliers['Monji ben Hamed'] ?? null],
            ['tirfond 8x50 (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['vis assemblage 5x50(eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['vis 4x40 jaune(eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['vis 4x20 blanc (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['manchon bargataire 25 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['scotch transparent +marron 100x48 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['verroux box 10 (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['rondelle 6x16x1mm (ahmed)', 0, 0, $suppliers['Ahmed'] ?? null],
            ['tayou gaz 6/12 (sicoplast)', 1, 1, null],
            ['raccord 16/1/2 m a visser amecap (omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['disque 125x1x22,2 tronc inox (Omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['niveau d\'eau 40 acem (omar)', 12, 12, $suppliers['Omar Abdelkefi'] ?? null],
            ['rivet 4x18 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['rivet 4,8x18 (monji)', 0, 0, $suppliers['Monji ben Hamed'] ?? null],
            ['mousqueton pompier 50 (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['mousqueton pompier 70 (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['tige cremoune renforcé jaune', 3, 3, null],
            ['vis th 12x40', 0, 0, null],
            ['vis th 10x50 8,8 noir', 0, 0, null],
            ['vis th 10x70 8,8 noir', 0, 0, null],
            ['manchon laiton 25x25 plast bleu sonede (monji)', 9, 9, $suppliers['Monji ben Hamed'] ?? null],
            ['serrure tiroir moneta m32 mts (monji)', 7, 7, $suppliers['Monji ben Hamed'] ?? null],
            ['silicone pattex blanc (monji)', 8, 8, $suppliers['Monji ben Hamed'] ?? null],
            ['pinceau 50 cristal (monji)', 4, 4, $suppliers['Monji ben Hamed'] ?? null],
            ['pinceau 60 cristal (monji)', 4, 4, $suppliers['Monji ben Hamed'] ?? null],
            ['bouchon pvc 63 socype (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['métre tuyau joly jaune 15 (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['boite enduit fleurtex 500g (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['support collecteur double 3/4', 4, 4, null],
            ['papier abrasif 120 guepard (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['serrure tiroir moneta m22 mts (monji)', 7, 7, $suppliers['Monji ben Hamed'] ?? null],
            ['cartouche mini antigoute cristal (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['serrure tiroir importé m22 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['reduction 80x63 imp (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['tube colle neoprene 70g tunisie colle (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['te pvc 100 (omar)', 3, 3, $suppliers['Omar Abdelkefi'] ?? null],
            ['papier abrasif 220 guepard (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['te pvc 100 (monji)', 4, 4, $suppliers['Monji ben Hamed'] ?? null],
            ['pinceau 30 cristal (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['métre barg sicoplus haute gamme (sicoplast)', 2, 2, null],
            ['boite sotumail 1 kg rouje (omar)', 10, 10, $suppliers['Omar Abdelkefi'] ?? null],
            ['charniere abattant lux plast (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['charniere invisible 1,5cm avec piston (Ahmed)', 2, 2, $suppliers['Ahmed'] ?? null],
            ['charniere invisible 1,5cm 3d (ahmed)', 2, 2, $suppliers['Ahmed'] ?? null],
            ['kg fil d\' attache hichem (ahmed)', 4, 4, $suppliers['Ahmed'] ?? null],
            ['support collecteur double 3/4 had (ahmed)', 4, 4, $suppliers['Ahmed'] ?? null],
            ['pinceau 40 cristal (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['serrure d\' armoire target ordinaire mts (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['serrure rideau ahram (monji)', 17, 17, $suppliers['Monji ben Hamed'] ?? null],
            ['serrure a tirage 100 ahram (monji)', 25, 25, $suppliers['Monji ben Hamed'] ?? null],
            ['te pvc 80 (monji)', 4, 4, $suppliers['Monji ben Hamed'] ?? null],
            ['cartouche melangeur carré amecap (omar)', 6, 6, $suppliers['Omar Abdelkefi'] ?? null],
            ['cartouche melangeur rond amecap (omar)', 5, 5, $suppliers['Omar Abdelkefi'] ?? null],
            ['vis 4x60 (eee)', 0, 0, null],
            ['bouchon pvc 50 (omar)', 1, 1, $suppliers['Omar Abdelkefi'] ?? null],
            ['riv bloc pt bravo nicklé (eechéque)', 10, 10, $suppliers['Euro Equipement'] ?? null],
            ['riv bloc gt bravo nicklé (eechéque)', 10, 10, $suppliers['Euro Equipement'] ?? null],
            ['riv bloc wc bravo nicklé (eechéque)', 11, 11, $suppliers['Euro Equipement'] ?? null],
            ['cadnas satine 50 mm extra (eechéque)', 6, 6, $suppliers['Euro Equipement'] ?? null],
            ['cadnas satine 62 mm extra (eechéque)', 9, 9, $suppliers['Euro Equipement'] ?? null],
            ['vis 4x50 (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['pate a vis 7X40 (had)', 0, 0, null],
            ['coude galv 26x34 ff (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['mamelon galv 33x42 monji)', 4, 4, null],
            ['monchon galv 26x33 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['monchon galv 33x42 (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['bobine etaint 1,5 mm 500g (monji)', 52, 52, $suppliers['Monji ben Hamed'] ?? null],
            ['marteau 300g brico (monji)', 7, 7, $suppliers['Monji ben Hamed'] ?? null],
            ['marteau 400g brico (monji)', 7, 7, $suppliers['Monji ben Hamed'] ?? null],
            ['marteau 500g brico (monji)', 8, 8, $suppliers['Monji ben Hamed'] ?? null],
            ['bonde receveur de douche 90 blanc ejim (monji)', 11, 11, $suppliers['Monji ben Hamed'] ?? null],
            ['bonde receveur de douche 90 chrommé ejim (monji)', 20, 20, $suppliers['Monji ben Hamed'] ?? null],
            ['douchette blanc lux plast (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['reduction pvc 63/50 plastex', 1, 1, null],
            ['vis 4x35 blanc (eeespece)', 0, 0, null],
            ['siphon plastique 25 x25 (had)', 6, 6, null],
            ['cadnas satine 32 mm extra (eechéque)', 2, 2, $suppliers['Euro Equipement'] ?? null],
            ['chignole 13 m 1050 w argess (eechéque)', 114, 114, $suppliers['Euro Equipement'] ?? null],
            ['métre tayou gaz as (ceg)', 2, 2, $suppliers['ceg'] ?? null],
            ['kit douchette imp (monji)', 5, 5, $suppliers['Monji ben Hamed'] ?? null],
            ['bande a vis 33 vis inox (lux plast)', 3, 3, null],
            ['siphon extensible 33 (lux plast)', 2, 2, null],
            ['vis th 12x50 8,8 noir (ahmed)', 0, 0, $suppliers['Ahmed'] ?? null],
            ['vis th 12x70 8,8 noir (ahmed)', 1, 1, $suppliers['Ahmed'] ?? null],
            ['vis th 8x80 (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['vis th 8x60 (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['vis th 12x40 ( eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['vis th 12x60 8,8 galv (ahmed)', 0, 0, $suppliers['Ahmed'] ?? null],
            ['flexible de douche pvc lux plast (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['flexible toilette chrommé sopal (monji)', 10, 10, $suppliers['Monji ben Hamed'] ?? null],
            ['robinet machine a laver 3/4 sopal (monji)', 17, 17, $suppliers['Monji ben Hamed'] ?? null],
            ['fixation 1 tige k2s (ayedi sanitaire)', 2, 2, $suppliers['Ramzi Ayedi'] ?? null],
            ['fixation 2 tige k2s (ayedi sanitaire)', 3, 3, $suppliers['Ramzi Ayedi'] ?? null],
            ['support moteur plastic k2s (ayedi sanitaire)', 5, 5, $suppliers['Ramzi Ayedi'] ?? null],
            ['charniere invisible 0,8 cm decor + (eechéque)', 1, 1, $suppliers['Euro Equipement'] ?? null],
            ['charniere invisible 1,5 cm decor + (eechéque)', 1, 1, $suppliers['Euro Equipement'] ?? null],
            ['vis 5x50 jaune(eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['vis 5x70 blanc (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['vis 5x40 jaune (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['vis 5x60 blanc (eechéque)', 0, 0, $suppliers['Euro Equipement'] ?? null],
            ['charniere invisible 1,5cm (naim)', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['console etager 150x200 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['manche marteau (naim makni)', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['paumelle a souder 100 (monji)', 3, 3, $suppliers['Monji ben Hamed'] ?? null],
            ['paumelle a souder 80 (monji)', 2, 2, $suppliers['Monji ben Hamed'] ?? null],
            ['resistance chauffe bain 80l-100 l (monji)', 20, 20, $suppliers['Monji ben Hamed'] ?? null],
            ['kg tv 4 sid (monji)', 6, 6, $suppliers['Monji ben Hamed'] ?? null],
            ['te pvc 125 (monji)', 8, 8, $suppliers['Monji ben Hamed'] ?? null],
            ['douchette bombe lux plast (omar)', 2, 2, $suppliers['Omar Abdelkefi'] ?? null],
            ['console de vitre gm haute qualité (had taieb console)', 1, 1, null],
            ['métre tayou gaz de ville (sicoplast)', 1, 1, null],
            ['ensemble de douche lux plast tressé (monji)', 8, 8, $suppliers['Monji ben Hamed'] ?? null],
            ['ensemle de douche lux plast pvc (monji)', 7, 7, $suppliers['Monji ben Hamed'] ?? null],
            ['riv bloc pt petek chrommé (monji)', 17, 17, $suppliers['Monji ben Hamed'] ?? null],
            ['riv bloc gt petek chrommé (monji)', 17, 17, $suppliers['Monji ben Hamed'] ?? null],
            ['riv bloc wc petek chrommé (monji)', 18, 18, $suppliers['Monji ben Hamed'] ?? null],
            ['support tube argent+dorré T27 simple (monji)', 1, 1, $suppliers['Monji ben Hamed'] ?? null],
            ['cartouche melangeur carré (monji)', 6, 6, $suppliers['Monji ben Hamed'] ?? null],
            ['support tube rideau chrommé rond', 1, 1, null],
            ['fixation chauffe bain k2s (ramzi ayedi)', 2, 2, $suppliers['Ramzi Ayedi'] ?? null],
            ['support micro onde (brahim)', 7, 7, null],
            ['rondelle 10x22x2,5 (brahim)', 0, 0, null],
            ['siphon plastic 25x25 ( ramzi ayedi)', 6, 6, $suppliers['Ramzi Ayedi'] ?? null],
            ['siphon plastic orientable 20x20 blanc (had)', 10, 10, null],
            ['pompe retouche or brillant ref 21(ceg)', 5, 5, $suppliers['ceg'] ?? null],
            ['pompe retouche noir brillant ref 02 (ceg)', 4, 4, $suppliers['ceg'] ?? null],
            ['duliant super qualité amal 1l (samir gouia)', 4, 4, $suppliers['Ami'] ?? null],
            ['couteau mastic 8cm inox mp (ceg)', 9, 9, $suppliers['ceg'] ?? null],
            ['pompe retouche blanc ref 01 (ceg)', 4, 4, $suppliers['ceg'] ?? null],
            ['pompe retouche rouge ref 04 (ceg)', 4, 4, $suppliers['ceg'] ?? null],
            ['pompe retouche argent chrommé ref 22 (ceg)', 5, 5, $suppliers['ceg'] ?? null],
            ['charniere espagnol d+g (ceg)', 1, 1, $suppliers['ceg'] ?? null],
            ['métre tayou vert avec fil importé (ceg)', 1, 1, $suppliers['ceg'] ?? null],
            ['tirfond 6x40 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['tirfond 6x80 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['tirphond 6x50 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['vis a bois 5x80 jaune (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['vis tr 5x60 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['ecrou 22 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['fil a plomb 600g (ceg)', 5, 5, $suppliers['ceg'] ?? null],
            ['Support tube argent T34 simple (ceg)', 1, 1, $suppliers['ceg'] ?? null],
            ['Support tube or T34 simple (ceg)', 1, 1, $suppliers['ceg'] ?? null],
            ['Support tube argent plafond 34 simple (ceg)', 2, 2, $suppliers['ceg'] ?? null],
            ['Support tube or plafond 34 simple (ceg)', 2, 2, $suppliers['ceg'] ?? null],
            ['vis th 8x80 4,8 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['bas de porte marron avec brosse (ceg)', 6, 6, $suppliers['ceg'] ?? null],
            ['bas de porte blanc avec brosse (ceg)', 6, 6, $suppliers['ceg'] ?? null],
            ['joint fibre 15/21 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['verroux box 10 (ceg)', 1, 1, $suppliers['ceg'] ?? null],
            ['vis alum 5x50 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['meche 12 diager (ceg)', 4, 4, $suppliers['ceg'] ?? null],
            ['regle de macon 2mx60x30', 26, 26, null],
            ['charniere fixe 90 (ceg)', 1, 1, $suppliers['ceg'] ?? null],
            ['balais contonner (naim) a,p', 3, 3, $suppliers['Naim Makni'] ?? null],
            ['brosse plafonner (naim) a,p', 3, 3, $suppliers['Naim Makni'] ?? null],
            ['cartouche mini laqué (naim) a,p', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['pinceau 20 (naim) a,p', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['pinceau 30 (naim) a,p', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['pinceau 40 (naim) a,p', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['pinceau 50 (naim) a,p', 1, 1, $suppliers['Naim Makni'] ?? null],
            ['pinceau 60 (naim) a,p', 2, 2, $suppliers['Naim Makni'] ?? null],
            ['pinceau 70 (naim) a,p', 2, 2, $suppliers['Naim Makni'] ?? null],
            ['pinceau rond n 6 (naim) a,p', 4, 4, $suppliers['Naim Makni'] ?? null],
            ['rouleau antigoute (naim) a,p', 4, 4, $suppliers['Naim Makni'] ?? null],
            ['rouleau mini laqué (naim) a,p', 2, 2, $suppliers['Naim Makni'] ?? null],
            ['rouleau ravallement (naim) a,p', 4, 4, $suppliers['Naim Makni'] ?? null],
            ['peton fermé 6x40 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['manche de ratteau (naim)', 2, 2, $suppliers['Naim Makni'] ?? null],
            ['manche de balais 1,5m (naim)', 3, 3, $suppliers['Naim Makni'] ?? null],
            ['tirefond 8x80 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['vis th 6x20 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['tirefond 6x70 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['tirefond 8x50 (ceg)', 0, 0, $suppliers['ceg'] ?? null],
            ['collection 3 pieces noir (ayedi sanitaire)', 18, 18, $suppliers['Ramzi Ayedi'] ?? null],
            ['collection 3 pieces beige (ayedi sanitaire)', 18, 18, $suppliers['Ramzi Ayedi'] ?? null],
        ];

        $code = 1;
        foreach ($products as [$name, $cost, $price, $supplier]) {
            Product::firstOrCreate(
                ['product_name' => $name],
                [
                    'category_id' => $category->id,
                    'supplier_id' => $supplier?->id,
                    'product_code' => 'LBP'.str_pad((string) $code, 5, '0', STR_PAD_LEFT),
                    'product_barcode_symbology' => 'C128',
                    'product_quantity' => 0,
                    'product_cost' => $cost,
                    'product_price' => $price,
                    'product_unit' => 'PC',
                    'product_stock_alert' => 1,
                    'product_order_tax' => 0,
                    'product_tax_type' => 1,
                ]
            );
            $code++;
        }
    }
}
